adjective1 = input("Enter an adjective :")
noun =input("Enter an noun :")
adjective2 =input("Enter an adjective :")
verb =input("Enter an verb :")
adjective3 =input("Enter an adjective :")

print(f"Today i went to a {adjective1} Zoo.")
print(f"In an Exhibit ,I saw a {noun}")
print(f"{noun} was {adjective2} and {verb}ing ")
print(f"I was {adjective3} ")
