name = "gokuldas"

print("name")
print(name)
print(f"name is : {name}")
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.count("o"))
print(name.replace("o","a"))
print(name.find("k"))
print(name.isdigit())
print(name.isalpha())
print(name*3)
print(len(name))